routes/web.php
<?php

Route::get('/', 'WelcomeController');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::impersonate();
});

# Public routes
Route::group(['prefix' => 'auction-vendors/{auction_code}', 'middleware' => ['auction.code_exists']], function () {
    Route::get('/', 'PublicAuctionVendorsController');
});

# Admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::resource('activities', 'Admin\ActivitiesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('users', 'Admin\UsersController', ['as' => 'admin'])
        ->only('index', 'edit', 'update');
    Route::resource('roles', 'Admin\RolesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('invites', 'Admin\InvitesController', ['as' => 'admin'])
        ->only('index', 'create', 'store');
    Route::post('invites/{invite}/resend', 'Admin\SendInvitesController')
        ->name('resend-invite')
        ->middleware(['can:invites.resend']);
});

# Main application routes including ajax
Route::group(['middleware' => ['auth', 'page-view.log']], function () {
    Route::resource('auctions', 'AuctionsController')
        ->only('index', 'create', 'store');
    Route::resource('donors', 'DonorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('school-families', 'SchoolFamiliesController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('vendors', 'VendorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::apiResource('vendor-imports', 'VendorFileImportsController')
        ->only('store');

    # Nested auction routes
    Route::resource('auctions.auction-items', 'AuctionItemsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.donations', 'AuctionDonationsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.school-families', 'AuctionSchoolFamiliesController')
        ->only('index');
    Route::resource('auctions.vendors', 'AuctionVendorsController')
        ->only('index');

    # Single action endpoints
    Route::post('donations/{donation}/approve', 'AuctionDonationApprovalsController')
        ->name('donation-approve')
        ->middleware('can:auction.donations.approve');
    Route::post('donations/{donation}/reject', 'AuctionDonationRejectsController')
        ->name('donation-reject')
        ->middleware('can:auction.donations.approve');

    # Ajax routes
    Route::group(['prefix' => 'ajax'], function () {
        Route::apiResource('auctions.vendor-registrations', 'Ajax\AuctionVendorRegistrationsController')
            ->only('store');
        Route::apiResource('auctions.vendors', 'Ajax\AuctionVendorsController', [
            'as' => 'ajax'
        ])
            ->only('update', 'index');
        Route::apiResource('auctions.auction-items', 'Ajax\AuctionItemsController', [
            'as' => 'ajax'
        ])
            ->only('index');
        Route::apiResource('donors', 'Ajax\DonorsController', [
            'as' => 'ajax'
        ])
            ->only('index', 'store');
        Route::post('auctions/{auction}/item-numbers-order', 'Ajax\AuctionItemNumbersOrderController', [
            'as' => 'ajax',
        ])->middleware(['can:auction.auction-items.reorder']);
    });
});

# Invitation routes
Route::group(['prefix' => 'invites/{token}/accept', 'middleware' => ['invite.valid', 'page-view.log']], function () {
    Route::get('/', 'InviteAcceptsController@create')->name('invite.view');
    Route::post('/', 'InviteAcceptsController@store')->name('invite.accept');
});

app/Models/SchoolFamily.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SchoolFamily extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $fillable = ['family_last_name', 'first_parent_name', 'second_parent_name'];

    /**
     * @var array
     */
    protected $appends = ['display_name'];

    /**
     * @return string
     */
    public function getDisplayNameAttribute()
    {
        $last_segment = [];

        if ($this->first_parent_name) {
            $last_segment[] = $this->first_parent_name;
        }

        if ($this->second_parent_name) {
            $last_segment[] = $this->second_parent_name;
        }

        $last_segment = implode(' & ', $last_segment);
        $parts        = [$this->family_last_name, $last_segment];

        return implode(', ', $parts);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function auctionVendors()
    {
        return $this->hasMany(AuctionVendor::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function auctions()
    {
        return $this->belongsToMany(Auction::class)->withTimestamps();
    }
}

app/Http/Controllers/SchoolFamiliesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateNewSchoolFamilyRequest;
use App\Http\Requests\UpdateSchoolFamilyRequest;
use App\Models\SchoolFamily;

class SchoolFamiliesController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:school-families.read')->only('index');
        $this->middleware('can:school-families.create')->only('create', 'store');
        $this->middleware('can:school-families.update')->only('edit', 'update');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $families = SchoolFamily::orderBy('family_last_name')->orderBy('first_parent_name')->get();

        return view('school-families.index', compact('families'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('school-families.create');
    }

    /**
     * @param CreateNewSchoolFamilyRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateNewSchoolFamilyRequest $req)
    {
        $family = SchoolFamily::create($req->all());

        return redirect()->route('school-families.index')->with('success', 'Created new family ' . $family->family_last_name);
    }

    /**
     * @param SchoolFamily $family
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(SchoolFamily $school_family)
    {
        return view('school-families.edit')->with(['family' => $school_family]);
    }

    /**
     * @param UpdateSchoolFamilyRequest $req
     * @param SchoolFamily $school_family
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateSchoolFamilyRequest $req, SchoolFamily $school_family)
    {
        $school_family->update($req->all());

        return redirect()->route('school-families.index')->with('success', 'Updated ' . $school_family->family_last_name . ' family');
    }
}

resources/views/school-families/create.blade.php
@extends('layouts.app')

@section('title', 'New Family | ')

@section('breadcrumbs')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{route('school-families.index')}}">School Families</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create Family</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="card nsca-card">
        <div class="card-header">
            <h3 class="card-title mb-0">New School Family</h3>
        </div>
        <div class="card-body">
            <form action="{{route('school-families.store')}}" method="POST">
                @csrf
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="family_last_name">Last Name</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('family_last_name'))is-invalid @endif"
                            value="{{old('family_last_name')}}"
                            placeholder="Smith"
                            type="text"
                            name="family_last_name"
                            id="family_last_name">
                        @if($errors->has('family_last_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('family_last_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="first_parent_name">First Parent</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('first_parent_name'))is-invalid @endif"
                            value="{{old('first_parent_name')}}"
                            placeholder="John"
                            type="text"
                            name="first_parent_name"
                            id="first_parent_name">
                        @if($errors->has('first_parent_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('first_parent_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="second_parent_name">Second Parent</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('second_parent_name'))is-invalid @endif"
                            value="{{old('second_parent_name')}}"
                            placeholder="Jane"
                            type="text"
                            name="second_parent_name"
                            id="second_parent_name">
                        @if($errors->has('second_parent_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('second_parent_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-md-8 offset-sm-3 offset-md-4">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/school-families/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Family | ')

@section('breadcrumbs')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{route('school-families.index')}}">School Families</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Family</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="card nsca-card">
        <div class="card-header">
            <h3 class="card-title mb-0">Edit School Family</h3>
        </div>
        <div class="card-body">
            <form action="{{route('school-families.update', $family)}}" method="POST">
                @csrf
                @method('put')
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="family_last_name">Last Name</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('family_last_name'))is-invalid @endif"
                            value="{{$family->family_last_name}}"
                            placeholder="Smith"
                            type="text"
                            name="family_last_name"
                            id="family_last_name">
                        @if($errors->has('family_last_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('family_last_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="first_parent_name">First Parent</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('first_parent_name'))is-invalid @endif"
                            value="{{$family->first_parent_name}}"
                            placeholder="John"
                            type="text"
                            name="first_parent_name"
                            id="first_parent_name">
                        @if($errors->has('first_parent_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('first_parent_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="second_parent_name">Second Parent</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('second_parent_name'))is-invalid @endif"
                            value="{{$family->second_parent_name}}"
                            placeholder="Jane"
                            type="text"
                            name="second_parent_name"
                            id="second_parent_name">
                        @if($errors->has('second_parent_name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('second_parent_name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-md-8 offset-sm-3 offset-md-4">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/school-families/index.blade.php
@extends('layouts.app')

@section('title', 'School Families | ')

@section('content')
    <div class="row mt-2">
        <div class="col">
            <div class="card nsca-card nsca-card__table">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h1 class="text-size-1_5 mb-0">School Families</h1>
                        @can('school-families.create')
                        <a href="{{route('school-families.create')}}" class="btn btn-primary">Add Family</a>
                        @endcan
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-responsive-xs table-nsca">
                        <thead>
                            <tr>
                                <th>Family</th>
                                <th>First Parent</th>
                                <th>Second Parent</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($families as $family)
                                <tr>
                                    <td>{{$family->family_last_name}}</td>
                                    <td>{{$family->first_parent_name}}</td>
                                    <td>{{$family->second_parent_name}}</td>
                                    <td class="text-right">
                                        <a class="btn btn-primary" href="{{route('school-families.edit', $family)}}">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection