routes/web.php
<?php

Route::get('/', 'WelcomeController');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::impersonate();
});

# Public routes
Route::group(['prefix' => 'auction-vendors/{auction_code}', 'middleware' => ['auction.code_exists']], function () {
    Route::get('/', 'PublicAuctionVendorsController');
});

# Admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::resource('activities', 'Admin\ActivitiesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('users', 'Admin\UsersController', ['as' => 'admin'])
        ->only('index', 'edit', 'update');
    Route::resource('roles', 'Admin\RolesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('invites', 'Admin\InvitesController', ['as' => 'admin'])
        ->only('index', 'create', 'store');
    Route::post('invites/{invite}/resend', 'Admin\SendInvitesController')
        ->name('resend-invite')
        ->middleware(['can:invites.resend']);
});

# Main application routes including ajax
Route::group(['middleware' => ['auth', 'page-view.log']], function () {
    Route::resource('auctions', 'AuctionsController')
        ->only('index', 'create', 'store');
    Route::resource('donors', 'DonorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('school-families', 'SchoolFamiliesController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('vendors', 'VendorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::apiResource('vendor-imports', 'VendorFileImportsController')
        ->only('store');

    # Nested auction routes
    Route::resource('auctions.auction-items', 'AuctionItemsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.donations', 'AuctionDonationsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.school-families', 'AuctionSchoolFamiliesController')
        ->only('index');
    Route::resource('auctions.vendors', 'AuctionVendorsController')
        ->only('index');

    # Single action endpoints
    Route::post('donations/{donation}/approve', 'AuctionDonationApprovalsController')
        ->name('donation-approve')
        ->middleware('can:auction.donations.approve');
    Route::post('donations/{donation}/reject', 'AuctionDonationRejectsController')
        ->name('donation-reject')
        ->middleware('can:auction.donations.approve');

    # Ajax routes
    Route::group(['prefix' => 'ajax'], function () {
        Route::apiResource('auctions.vendor-registrations', 'Ajax\AuctionVendorRegistrationsController')
            ->only('store');
        Route::apiResource('auctions.vendors', 'Ajax\AuctionVendorsController', [
            'as' => 'ajax'
        ])
            ->only('update', 'index');
        Route::apiResource('auctions.auction-items', 'Ajax\AuctionItemsController', [
            'as' => 'ajax'
        ])
            ->only('index');
        Route::apiResource('donors', 'Ajax\DonorsController', [
            'as' => 'ajax'
        ])
            ->only('index', 'store');
        Route::post('auctions/{auction}/item-numbers-order', 'Ajax\AuctionItemNumbersOrderController', [
            'as' => 'ajax',
        ])->middleware(['can:auction.auction-items.reorder']);
    });
});

# Invitation routes
Route::group(['prefix' => 'invites/{token}/accept', 'middleware' => ['invite.valid', 'page-view.log']], function () {
    Route::get('/', 'InviteAcceptsController@create')->name('invite.view');
    Route::post('/', 'InviteAcceptsController@store')->name('invite.accept');
});

app/Models/Donor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Donor extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @return mixed
     */
    public function getFirstNameAttribute()
    {
        $parts = explode(' ', $this->attributes['name'], 2);

        return collect($parts)->filter(function($p) {
            return !empty($p);
        })->first();
    }

    /**
     * @return mixed
     */
    public function getLastNameAttribute()
    {
        $parts = explode(' ', $this->attributes['name'], 2);

        return collect($parts)->filter(function($p) {
            return !empty($p);
        })->last();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function donations()
    {
        return $this->morphMany(Donation::class, 'donor');
    }
}

app/Http/Controllers/Ajax/DonorsController.php
<?php

namespace App\Http\Controllers\Ajax;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateDonorRequest;
use App\Http\Resources\Donor as DonorResource;
use App\Http\Resources\DonorCollection;
use App\Models\Donor;

class DonorsController extends Controller
{
    /**
     * @return DonorCollection
     */
    public function index()
    {
        $donors = Donor::orderBy('name')->get();

        return new DonorCollection($donors);
    }

    /**
     * @param CreateDonorRequest $req
     * @return DonorResource
     */
    public function store(CreateDonorRequest $req)
    {
        $donor = Donor::create($req->all());

        return new DonorResource($donor);
    }
}

app/Http/Controllers/DonorsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateDonorRequest;
use App\Http\Requests\UpdateDonorRequest;
use App\Models\Donor;

class DonorsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:donors.read')->only('index');
        $this->middleware('can:donors.create')->only('create', 'store');
        $this->middleware('can:donors.update')->only('edit', 'update');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $donors = Donor::orderBy('name')->get();

        return view('donors.index', compact('donors'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('donors.create');
    }

    /**
     * @param CreateDonorRequest $req
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateDonorRequest $req)
    {
        $donor = Donor::create($req->all());

        return redirect()->route('donors.index')->with('success', 'Donor created: ' . $donor->name);
    }

    /**
     * @param Donor $donor
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Donor $donor)
    {
        return view('donors.edit')->with(compact('donor'));
    }

    /**
     * @param UpdateDonorRequest $req
     * @param Donor $donor
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateDonorRequest $req, Donor $donor)
    {
        $donor->update($req->all());

        return redirect()->route('donors.index')->with('success', 'Donor updated: ' . $donor->name);
    }
}

resources/views/donors/create.blade.php
@extends('layouts.app')

@section('title', 'New Donor | ')

@section('breadcrumbs')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{route('donors.index')}}">Donors</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create Donor</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="card nsca-card">
        <div class="card-header">
            <h3 class="card-title mb-0">New Donor</h3>
        </div>
        <div class="card-body">
            <form action="{{route('donors.store')}}" method="POST">
                @csrf
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="name">Name</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('name'))is-invalid @endif"
                            value="{{old('name')}}"
                            placeholder="Homestar Runner"
                            type="text"
                            name="name"
                            id="name">
                        @if($errors->has('name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="email">Email</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('email'))is-invalid @endif"
                            value="{{old('email')}}"
                            placeholder="gmail@aol.com"
                            type="email"
                            name="email"
                            id="email">
                        @if($errors->has('email'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('email') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right col-md-4" for="phone">Phone</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('phone'))is-invalid @endif"
                            value="{{old('phone')}}"
                            placeholder="(123)456-1234"
                            type="tel"
                            name="phone"
                            id="phone">
                        @if($errors->has('phone'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('phone') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-md-8 offset-sm-3 offset-md-4">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/donors/edit.blade.php
@extends('layouts.app')

@section('title', 'Update Donor | ')

@section('breadcrumbs')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{{route('donors.index')}}">Donors</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Donor</li>
        </ol>
    </nav>
@endsection

@section('content')
    <div class="card nsca-card">
        <div class="card-header">
            <h3 class="card-title mb-0">Edit Donor</h3>
        </div>
        <div class="card-body">
            <form action="{{route('donors.update', $donor)}}" method="POST">
                @csrf
                @method('put')
                <div class="form-group row">
                    <label class="col-form-label text-md-right col-sm-3 col-md-4" for="name">Name</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('name'))is-invalid @endif"
                            value="{{$donor->name}}"
                            placeholder="Homestar Runner"
                            type="text"
                            name="name"
                            id="name">
                        @if($errors->has('name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label text-md-right col-sm-3 col-md-4" for="email">Email</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('email'))is-invalid @endif"
                            value="{{$donor->email}}"
                            placeholder="gmail@aol.com"
                            type="email"
                            name="email"
                            id="email">
                        @if($errors->has('email'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('email') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label text-md-right col-sm-3 col-md-4" for="phone">Phone</label>
                    <div class="col-sm-9 col-md-8">
                        <input
                            class="form-control @if($errors->has('phone'))is-invalid @endif"
                            value="{{$donor->phone}}"
                            placeholder="(123)456-1234"
                            type="tel"
                            name="phone"
                            id="phone">
                        @if($errors->has('phone'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('phone') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 col-md-8 offset-sm-3 offset-md-4">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/donors/index.blade.php
@extends('layouts.app')

@section('title', 'Donors | ')

@section('content')
    <div class="row mt-2">
        <div class="col">
            <div class="card nsca-card nsca-card__table">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h1 class="text-size-1_5 mb-0">Donors</h1>
                        @can('donors.create')
                        <a href="{{route('donors.create')}}" class="btn btn-primary">Add Donor</a>
                        @endcan
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-responsive-lg table-nsca">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($donors as $donor)
                                <tr>
                                    <td>{{$donor->name}}</td>
                                    <td>{{$donor->email}}</td>
                                    <td>{{$donor->phone}}</td>
                                    <td class="text-right">
                                        @can('donors.update')
                                        <a href="{{route('donors.edit', $donor)}}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection