routes/web.php
<?php

Route::get('/', 'WelcomeController');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::impersonate();
});

# Public routes
Route::group(['prefix' => 'auction-vendors/{auction_code}', 'middleware' => ['auction.code_exists']], function () {
    Route::get('/', 'PublicAuctionVendorsController');
});

# Admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::resource('activities', 'Admin\ActivitiesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('users', 'Admin\UsersController', ['as' => 'admin'])
        ->only('index', 'edit', 'update');
    Route::resource('roles', 'Admin\RolesController', ['as' => 'admin'])
        ->only('index');
    Route::resource('invites', 'Admin\InvitesController', ['as' => 'admin'])
        ->only('index', 'create', 'store');
    Route::post('invites/{invite}/resend', 'Admin\SendInvitesController')
        ->name('resend-invite')
        ->middleware(['can:invites.resend']);
});

# Main application routes including ajax
Route::group(['middleware' => ['auth', 'page-view.log']], function () {
    Route::resource('auctions', 'AuctionsController')
        ->only('index', 'create', 'store');
    Route::resource('donors', 'DonorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('school-families', 'SchoolFamiliesController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('vendors', 'VendorsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::apiResource('vendor-imports', 'VendorFileImportsController')
        ->only('store');

    # Nested auction routes
    Route::resource('auctions.auction-items', 'AuctionItemsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.donations', 'AuctionDonationsController')
        ->only('index', 'create', 'store', 'edit', 'update');
    Route::resource('auctions.school-families', 'AuctionSchoolFamiliesController')
        ->only('index');
    Route::resource('auctions.vendors', 'AuctionVendorsController')
        ->only('index');

    # Single action endpoints
    Route::post('donations/{donation}/approve', 'AuctionDonationApprovalsController')
        ->name('donation-approve')
        ->middleware('can:auction.donations.approve');
    Route::post('donations/{donation}/reject', 'AuctionDonationRejectsController')
        ->name('donation-reject')
        ->middleware('can:auction.donations.approve');

    # Ajax routes
    Route::group(['prefix' => 'ajax'], function () {
        Route::apiResource('auctions.vendor-registrations', 'Ajax\AuctionVendorRegistrationsController')
            ->only('store');
        Route::apiResource('auctions.vendors', 'Ajax\AuctionVendorsController', [
            'as' => 'ajax'
        ])
            ->only('update', 'index');
        Route::apiResource('auctions.auction-items', 'Ajax\AuctionItemsController', [
            'as' => 'ajax'
        ])
            ->only('index');
        Route::apiResource('donors', 'Ajax\DonorsController', [
            'as' => 'ajax'
        ])
            ->only('index', 'store');
        Route::post('auctions/{auction}/item-numbers-order', 'Ajax\AuctionItemNumbersOrderController', [
            'as' => 'ajax',
        ])->middleware(['can:auction.auction-items.reorder']);
    });
});

# Invitation routes
Route::group(['prefix' => 'invites/{token}/accept', 'middleware' => ['invite.valid', 'page-view.log']], function () {
    Route::get('/', 'InviteAcceptsController@create')->name('invite.view');
    Route::post('/', 'InviteAcceptsController@store')->name('invite.accept');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Lab404\Impersonate\Models\Impersonate;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, Impersonate;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return bool
     */
    public function canImpersonate()
    {
        return $this->roles->pluck('name')->contains('super-admin');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUserProfileRequest;
use App\Models\User;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{
    /**
     * UsersController constructor.
     */
    public function __construct()
    {
        $this->middleware(['can:users.read'])->only('index');
        $this->middleware(['can:users.update'])->only('edit', 'update');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = User::orderBy('name')->get();

        return view('admin.users.index')->with(compact('users'));
    }

    /**
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(User $user)
    {
        $roles = Role::orderBy('name')->get();

        return view('admin.users.edit')->with(compact('user', 'roles'));
    }

    /**
     * @param UpdateUserProfileRequest $req
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateUserProfileRequest $req, User $user)
    {
        $user->update([
            'name'  => $req->get('name'),
            'email' => $req->get('email')
        ]);

        if($req->has('roles')) {
            $user->syncRoles($req->get('roles'));
        }

        return redirect()->route('admin.users.index')->with('success', 'Updated ' . $user->name);
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit User | ')

@section('rightContent')
    <div class="card nsca-card mt-4 mt-md-0">
        <div class="card-header">
            <h4 class="card-title mb-0">Profile</h4>
        </div>
        <div class="card-body">
            <form action="{{route('admin.users.update', $user)}}" method="POST">
                @csrf
                @method('put')
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right" for="name">Name</label>
                    <div class="col-sm-9">
                        <input
                            class="form-control @if($errors->has('name'))is-invalid @endif"
                            value="{{old('name') ? old('name') : $user->name}}"
                            placeholder="John"
                            type="text"
                            name="name"
                            id="name">
                        @if($errors->has('name'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('name') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right" for="email">Email</label>
                    <div class="col-sm-9">
                        <input
                            class="form-control @if($errors->has('email'))is-invalid @endif"
                            value="{{old('email') ? old('email') : $user->email}}"
                            placeholder="gmail@aol.com"
                            type="email"
                            name="email"
                            id="email">
                        @if($errors->has('email'))
                            <div class="invalid-feedback">
                                @foreach($errors->get('email') as $error)
                                    <div>
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-form-label col-sm-3 text-md-right" for="name">Roles</label>
                    <div class="col-sm-9">
                        <div class="row">
                            @foreach($roles as $role)
                                <div class="col-sm-4">
                                    <label for="role-{{$role->id}}">
                                        <input type="checkbox" value="{{$role->id}}" id="role-{{$role->id}}" name="roles[]" @if($user->roles->contains($role->id))checked @endif>
                                        {{ucfirst($role->name)}}
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-9 offset-3">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Users | ')

@section('rightContent')
<div class="card nsca-card nsca-card__table">
    <div class="card-header">
        <h4 class="mb-0">Current Users</h4>
    </div>
    <div class="card-body">
        <table class="table table-nsca">
            <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <td class="text-center">{{$user->id}}</td>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->roles->pluck('name')->implode(', ')}}</td>
                        <td class="text-center">
                            <a class="btn btn-outline-primary" href="{{route('admin.users.edit', $user)}}">
                                <i class="fa fa-pencil"></i>
                            </a>
                            @if(!$user->is(auth()->user()))
                            <a href="{{route('impersonate', $user->id)}}" class="btn btn-outline-primary">
                                <i class="fa fa-user-secret"></i>
                            </a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection